name: Terraform CI
on:
  push:
    branches:
    - main
    - dev
  pull_request:

jobs:
  tflint:
    name: Terraform Linter
    runs-on: ubuntu-22.04
    steps:
    -
      uses: actions/checkout@v3
      name: Checkout source code
    -
      uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: v0.44.1
    -
      name: Show version
      run: tflint --version
    -
      name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ github.token }}
    -
      name: Run TFLint
      run: tflint -f compact
